name: Text2Measurements tests

on:
  push:
    paths:
      - 'libs/text-2-measurements/**'
  pull_request:
    paths:
      - 'libs/text-2-measurements/**'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install Dependencies
        run: |
          cd libs/text-2-measurements
          npm ci

      - name: Run Tests
        run: |
          cd libs/text-2-measurements
          npm test
